"""fix_relationship_foreign_keys atempt 2

Revision ID: 9e2dfd1fc315
Revises: e3955060f98e
Create Date: 2024-11-11 17:00:18.463176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2dfd1fc315'
down_revision: Union[str, None] = 'e3955060f98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
