"""added audit fields

Revision ID: e3955060f98e
Revises: 66751f58519e
Create Date: 2024-11-11 16:47:43.484629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3955060f98e'
down_revision: Union[str, None] = '66751f58519e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_questions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('ai_questions', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('ai_questions', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ai_questions', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'ai_questions', 'users', ['updated_by_id'], ['id'])
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('comments', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['created_by_id'], ['id'])
    op.add_column('events', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('events', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['updated_by_id'], ['id'])
    op.add_column('merchandise', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('merchandise', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('merchandise', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('merchandise', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'merchandise', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'merchandise', 'users', ['updated_by_id'], ['id'])
    op.add_column('order_items', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('order_items', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('order_items', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'users', ['updated_by_id'], ['id'])
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('orders', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['updated_by_id'], ['id'])
    op.add_column('photos', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('photos', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('photos', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photos', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'photos', 'users', ['updated_by_id'], ['id'])
    op.add_column('registrations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('registrations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('registrations', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('registrations', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'registrations', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'registrations', 'users', ['created_by_id'], ['id'])
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'updated_by_id')
    op.drop_column('users', 'created_by_id')
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_column('registrations', 'updated_by_id')
    op.drop_column('registrations', 'created_by_id')
    op.drop_column('registrations', 'updated_at')
    op.drop_column('registrations', 'created_at')
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'updated_by_id')
    op.drop_column('photos', 'created_by_id')
    op.drop_column('photos', 'updated_at')
    op.drop_column('photos', 'created_at')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'updated_by_id')
    op.drop_column('orders', 'created_by_id')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'updated_by_id')
    op.drop_column('order_items', 'created_by_id')
    op.drop_column('order_items', 'updated_at')
    op.drop_column('order_items', 'created_at')
    op.drop_constraint(None, 'merchandise', type_='foreignkey')
    op.drop_constraint(None, 'merchandise', type_='foreignkey')
    op.drop_column('merchandise', 'updated_by_id')
    op.drop_column('merchandise', 'created_by_id')
    op.drop_column('merchandise', 'updated_at')
    op.drop_column('merchandise', 'created_at')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'updated_by_id')
    op.drop_column('events', 'created_by_id')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'updated_by_id')
    op.drop_column('comments', 'created_by_id')
    op.drop_column('comments', 'updated_at')
    op.drop_constraint(None, 'ai_questions', type_='foreignkey')
    op.drop_constraint(None, 'ai_questions', type_='foreignkey')
    op.drop_column('ai_questions', 'updated_by_id')
    op.drop_column('ai_questions', 'created_by_id')
    op.drop_column('ai_questions', 'updated_at')
    # ### end Alembic commands ###
